// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
  if (a0 == 0xc || a0 == 0xb) {
    char buf[128];
    sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1,
            (uint8_t)a2);
    return open(buf, O_RDWR, 0);
  } else {
    unsigned long nb = a1;
    char buf[1024];
    char* hash;
    strncpy(buf, (char*)a0, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = 0;
    while ((hash = strchr(buf, '#'))) {
      *hash = '0' + (char)(nb % 10);
      nb /= 10;
    }
    return open(buf, a2 & ~O_CREAT, 0);
  }
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  syz_open_dev$I2C arguments: [
  //    dev: ptr[in, buffer] {
  //      buffer: {2f 64 65 76 2f 69 32 63 2d 23 00} (length 0xb)
  //    }
  //    id: intptr = 0x7d0 (8 bytes)
  //    flags: open_flags = 0x0 (8 bytes)
  //  ]
  //  returns fd_i2c
  memcpy((void*)0x2000000008c0, "/dev/i2c-#\000", 11);
  syz_open_dev(/*dev=*/0x2000000008c0, /*id=*/0x7d0, /*flags=*/0);
  //  syz_open_dev$I2C arguments: [
  //    dev: ptr[in, buffer] {
  //      buffer: {2f 64 65 76 2f 69 32 63 2d 23 00} (length 0xb)
  //    }
  //    id: intptr = 0x0 (8 bytes)
  //    flags: open_flags = 0x8b9310ef64340306 (8 bytes)
  //  ]
  //  returns fd_i2c
  memcpy((void*)0x200000000000, "/dev/i2c-#\000", 11);
  res = -1;
  res = syz_open_dev(
      /*dev=*/0x200000000000, /*id=*/0,
      /*flags=O_TRUNC|O_PATH|O_NOCTTY|O_NOATIME|O_RDWR|0x8b9310ef64100004*/
      0x8b9310ef64340306);
  if (res != -1)
    r[0] = res;
  //  ioctl$I2C_SMBUS arguments: [
  //    fd: fd_i2c (resource)
  //    cmd: const = 0x401c5820 (4 bytes)
  //    arg: nil
  //  ]
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x401c5820, /*arg=*/0ul);
  //  syz_open_dev$I2C arguments: [
  //    dev: ptr[in, buffer] {
  //      buffer: {2f 64 65 76 2f 69 32 63 2d 23 00} (length 0xb)
  //    }
  //    id: intptr = 0x0 (8 bytes)
  //    flags: open_flags = 0x22000 (8 bytes)
  //  ]
  //  returns fd_i2c
  memcpy((void*)0x200000000280, "/dev/i2c-#\000", 11);
  res = -1;
  res = syz_open_dev(/*dev=*/0x200000000280, /*id=*/0,
                     /*flags=O_NOFOLLOW|FASYNC*/ 0x22000);
  if (res != -1)
    r[1] = res;
  //  ioctl$I2C_SMBUS arguments: [
  //    fd: fd_i2c (resource)
  //    cmd: const = 0x720 (4 bytes)
  //    arg: ptr[in, i2c_smbus_ioctl_data] {
  //      i2c_smbus_ioctl_data {
  //        read_write: int8 = 0x0 (1 bytes)
  //        command: int8 = 0x40 (1 bytes)
  //        pad = 0x0 (2 bytes)
  //        size: int32 = 0x2 (4 bytes)
  //        data: nil
  //      }
  //    }
  //  ]
  *(uint8_t*)0x200000000040 = 0;
  *(uint8_t*)0x200000000041 = 0x40;
  *(uint32_t*)0x200000000044 = 2;
  *(uint64_t*)0x200000000048 = 0;
  syscall(__NR_ioctl, /*fd=*/r[1], /*cmd=*/0x720, /*arg=*/0x200000000040ul);
  //  syz_open_dev$I2C arguments: [
  //    dev: ptr[in, buffer] {
  //      buffer: {2f 64 65 76 2f 69 32 63 2d 23 00} (length 0xb)
  //    }
  //    id: intptr = 0x0 (8 bytes)
  //    flags: open_flags = 0x787a00 (8 bytes)
  //  ]
  //  returns fd_i2c
  memcpy((void*)0x200000000040, "/dev/i2c-#\000", 11);
  res = -1;
  res = syz_open_dev(
      /*dev=*/0x200000000040, /*id=*/0,
      /*flags=__O_TMPFILE|O_TRUNC|O_SYNC|O_PATH|O_NONBLOCK|O_DIRECT|O_CLOEXEC|0x2000*/
      0x787a00);
  if (res != -1)
    r[2] = res;
  //  ioctl$I2C_SMBUS arguments: [
  //    fd: fd_i2c (resource)
  //    cmd: const = 0x720 (4 bytes)
  //    arg: nil
  //  ]
  syscall(__NR_ioctl, /*fd=*/r[2], /*cmd=*/0x720, /*arg=*/0ul);
  //  syz_open_dev$I2C arguments: [
  //    dev: ptr[in, buffer] {
  //      buffer: {2f 64 65 76 2f 69 32 63 2d 23 00} (length 0xb)
  //    }
  //    id: intptr = 0x875a (8 bytes)
  //    flags: open_flags = 0xa4a01 (8 bytes)
  //  ]
  //  returns fd_i2c
  memcpy((void*)0x200000000000, "/dev/i2c-#\000", 11);
  syz_open_dev(
      /*dev=*/0x200000000000, /*id=*/0x875a,
      /*flags=O_TRUNC|O_NONBLOCK|O_NOFOLLOW|O_DIRECT|O_CLOEXEC|O_WRONLY*/
      0xa4a01);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  for (procid = 0; procid < 4; procid++) {
    if (fork() == 0) {
      loop();
    }
  }
  sleep(1000000);
  return 0;
}
